app = "telegram-bot-mfitfq"
primary_region = "syd"

[build]
  # Dockerfile is used by default

[processes]
  app = "python bot.py"

[vm]
  size = "shared-cpu-1x"
  memory = "256mb"

[scale]
  min = 1
  max = 1
